dispositivo1: {
    rele: 11,
    sensor_corrente: 97,
    sensor_voltagem: 90,
    display_clk: 2,
    display_dio: 3,
},
dispositivo2: {
    rele: 13,
    sensor_corrente: 85,
    sensor_voltagem: 91,
    display_clk: 4,
    display_dio: 5,
},
